---
title: "Gov 50 Final Project"
author: "King Machain"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---

## Project thoughts

I am interested in exploring data related to sports and how athlete performance, fan base, previous accolades, etc. relate to their salaries / contracts. I believe that a players performance is only part of the equation when it comes to salaries, and that the ability to sell tickets may be an even more important factor. I want to find a way to make my project more impactful and make more meaningful conclusions, and I am brainstorming on how to take my statistical analysis deeper.

##Proposal

How is player performance reflected in player salaries in the MLB? In this study, I plan to examine the extent to which player performance results in changes in salary. I hypothesize that player salaries increase as player performance increases. It is likely that MLB players with successful performance statistics are higher paid than those who underperform. While I believe this will be true, I expect that this is only true for players that have played for more than 6 years in the league and reach free agency. This is because before reaching free agency, players are rarely paid more than the league minimum, as players don’t have bargaining power to negotiate a better deal until free agency. My sample consists of 3 datasets: Batting statistics by player for the 2023 season, Pitching statistics by player for the 2023 season, and up-to-date player salaries. The explanatory variables consider player performance: TB (total bases), OPS (on-base plus slugging percentage), ERA (earned run average), WHIP (walks + hits/innings pitched). Each of these variables is measured with a numeric value from the formulas described above. My outcome variable is player salary, a numeric value for the amount of money a player is paid for a season. If I observe higher player salaries for players with better statistics in the explanatory variables, this would support my hypothesis. However, if I observe lower salaries or no correlation for high performing players, this would be evidence against my hypothesis.  When I run my regression of player performance on the player salary variable, a positive, significant coefficient would indicate support for my hypothesis. One thing to take into consideration are intangible variables that contribute to a player’s salary such as popularity, attitude, and image.

